### PR TITLE
feat(js): fix tracing of subagents for newer versions of @anthropic/claude-agent-sdk, harden null checks

### LINKED ISSUE #2610: JS: wrapClaudeAgentSDK crashes on subagents — isTaskTool checks for "Task" but SDK emits "Agent"
### Bug

`wrapClaudeAgentSDK` (JS) crashes when the Claude Agent SDK dispatches a subagent. The `isTaskTool` function in `js/src/experimental/anthropic/messages.ts` checks `tool.name === "Task"`, but current SDK releases emit `"Agent"` in `tool_use` blocks.

This causes `StreamManager.addMessage` to skip registering the namespace for the subagent's `tool_use_id`, so when the subagent's first message arrives with `parent_tool_use_id`, `this.namespaces[namespace]` is `undefined` and `createChild` throws:

```
TypeError: Cannot read properties of undefined (reading 'createChild')
    at StreamManager.createChild
    at StreamManager.addMessage
```

### From the Claude Agent SDK docs

> The tool name was renamed from "Task" to "Agent" in Claude Code v2.1.63. Current SDK releases emit "Agent" in tool_use blocks but still use "Task" in the system:init tools list and in result.permission_denials[].tool_name. Checking both values in block.name ensures compatibility across SDK versions.

Source: https://platform.claude.com/docs/en/agent-sdk/subagents

### Fix

`isTaskTool` in `js/src/experimental/anthropic/messages.ts` should check for both names:

```typescript
export function isTaskTool(tool: BetaToolUseBlock) {
  return tool.type === "tool_use" && (tool.name === "Task" || tool.name === "Agent");
}
```

### Reproduction

```typescript
import * as claudeAgentSdk from "@anthropic-ai/claude-agent-sdk";
import { wrapClaudeAgentSDK } from "langsmith/experimental/anthropic";

const { query } = wrapClaudeAgentSDK(claudeAgentSdk, {});

for await (const message of query({
  prompt: "Use the committer agent to commit changes",
  options: {
    allowedTools: ["Bash", "Agent"],
    agents: {
      committer: {
        description: "Commits code changes",
        tools: ["Bash"],
        prompt: "Run git status and commit all changes.",
      },
    },
  },
})) {
  // Crashes when subagent dispatches
}
```

### Environment

- `langsmith`: 0.5.13
- `@anthropic-ai/claude-agent-sdk`: 0.2.71
- Node.js 22

### PR DESCRIPTION
**Pull request by dqbd**
Closes #2610

### CODE REVIEW

File: js/src/experimental/anthropic/context.ts [hunk 1]
```diff
@@ -193,7 +197,7 @@ export class StreamManager {
               ? getToolError(result)
               : undefined;
 
-          void this.tools[block.tool_use_id].end(toolOutput, toolError);
+          void this.tools[block.tool_use_id]?.end(toolOutput, toolError);
```
Comment (jacoblee93) [inline js/src/experimental/anthropic/context.ts:200]: It actually is not harmful to await this it's fast

Comment (dqbd) [reply js/src/experimental/anthropic/context.ts:200]: The function is synchronous and don't think worth perf impact to await
